### ISSUE TITLE
你好为什么和arouter 一起使用会报： E/XStarterHelper: 没有找到XStart初始化类 错误呢

### ISSUE THREAD

**Issue by bimromatic** [wangkunhui/XStarter#1]

**Comment by wangkunhui** [comment]
使用注解之后，需要rebuild一下项目，这样apt才能生成类文件，看是否是没有rebuild导致的

**Comment by bimromatic** [comment]
谢谢，感觉兄弟的这种基于apt 的方案，相对于异步初始化这种性能稍微低一点，经过大概差了500ms ，不过这种方案相对于组件化这种application 去中心化 的方案，兄弟的想法还是蛮好的，最后谢谢分享，让我学习了一波。

**Comment by wangkunhui** [comment]
是的，首次启动或debug为true的时候会从dex中检索生成的文件，这个比较耗时，不过有缓存机制的，非debug第二次打开就不需要检索了，速度也会快很多。这个地方参考的arouter的实现逻辑。
